components:
  schemas:
    User:
      type: object
      properties:
        user_email:
          type: string
          description: ì‚¬ìš©ì email
          example: testemail@google.com
        user_password:
          type: string
          description: ì‚¬ìš©ì ë¹„ë°€ë²ˆí˜¸
          example: 1q2w3e4r!
        user_nickname:
          type: string
          description: ì‚¬ìš©ì ë‹‰ë„¤ì„
          example: ì”€ì”€ì´ìš©ì
        user_birth:
          type: string # íƒ€ì…ì€ string
          format: date # ğŸ’¡ format: dateë¡œ ë‚ ì§œ í˜•ì‹ ì§€ì •
          description: ì‚¬ìš©ì ìƒì¼ (YYYY-MM-DD)
          example: "1995-12-25"
        user_gender:
          type: string
          description: ì‚¬ìš©ì ì„±ë³„
          example: ë‚¨

    Asset:
      type: object
      properties:
        asset_name:
          type: string
          description: ìì‚° ì´ë¦„
          example: KBêµ­ë¯¼ì€í–‰ ê³„ì¢Œ
        asset_type:
          type: string
          description: ìì‚° ì¢…ë¥˜
          example: ì ê¸ˆê³„ì¢Œ
        asset_amount:
          type: number
          description: ìì‚° ê¸ˆì•¡
          example: 300000

    Budget:
      type: object
      properties:
        budget_name:
          type: string
          description: ì˜ˆì‚° ì´ë¦„
          example: 10ì›” ì˜ˆì‚°
        budget_month:
          type: string
          description: ì˜ˆì‚° ì›”
          example: "2023-10"
        budget_total:
          type: Number
          description: ì´ ì˜ˆì‚° ê¸ˆì•¡
          example: 10000000

        budget_categories:
          type: array
          items:
            type: object
            properties:
              category_id:
                type: string
                description: ì¹´í…Œê³ ë¦¬ ID
                example: 5a76gfq23raf6glkaef
              budget_amount:
                type: number
                description: ì¹´í…Œê³ ë¦¬ë³„ ì˜ˆì‚° ê¸ˆì•¡
                example: 2000000

    Category:
      type: object
      properties:
        category_name:
          type: string
          description: ì¹´í…Œê³ ë¦¬ ì´ë¦„
          example: ì‹ë¹„
        category_type:
          type: string
          description: ì¹´í…Œê³ ë¦¬ ì¢…ë¥˜ (ìˆ˜ì…/ì§€ì¶œ)
          example: ì§€ì¶œ

    Transaction:
      type: object
      properties:
        transaction_name:
          type: string
          description: ê±°ë˜ë‚´ì—­ ì´ë¦„
          example: ì ì‹¬ ì‹ì‚¬
        transaction_amount:
          type: number
          description: ê±°ë˜ ê¸ˆì•¡
          example: 15000
        transaction_type:
          type: string
          description: ê±°ë˜ ì¢…ë¥˜ (ìˆ˜ì…/ì§€ì¶œ)
          example: ì§€ì¶œ
        transaction_datetime:
          type: string # íƒ€ì…ì€ string
          format: date # ğŸ’¡ format: dateë¡œ ë‚ ì§œ í˜•ì‹ ì§€ì •
          description: ê±°ë˜ ë‚ ì§œ (YYYY-MM-DD)
          example: "2023-10-01 hh:mm:ss"
        transaction_assetId:
          type: string
          description: ê±°ë˜ ìì‚° ID
          example: 1234567890abcdef
        transaction_category_id:
          type: string
          description: ì¹´í…Œê³ ë¦¬ ID
          example: 5a76gfq23raf6glkaef
